name: Code Quality

on:
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy black isort

    - name: Check code formatting with black
      run: |
        black --check --diff custom_components/ tests/

    - name: Check import sorting with isort
      run: |
        isort --check-only --diff custom_components/ tests/

    - name: Lint with flake8
      run: |
        flake8 custom_components/ tests/

    - name: Type check with mypy
      run: |
        mypy custom_components/nsw_air_quality/
      continue-on-error: true
